DROP SCHEMA PUBLIC CASCADE;
DROP TABLE IF EXISTS user;
CREATE TABLE IF NOT EXISTS user (
    id int GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    nom varchar(25) NOT NULL,
    prenom varchar(25) NOT NULL,
    telephone varchar(25),
    email varchar(50) NOT NULL UNIQUE,
    adresse1 varchar(25),
    adresse2 varchar(25),
    ville varchar(25),
    cp varchar(25),
    password_hash varchar(255) NOT NULL,
    salt varchar(255) NOT NULL,
    type varchar(20) NOT NULL,
    role varchar(50) NOT NULL,
    validated boolean NOT NULL,
    PRIMARY KEY (id)
);
DROP TABLE IF EXISTS "admin";
CREATE TABLE IF NOT EXISTS "ADMIN" (
    id int NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (id) REFERENCES user (id)
);
DROP TABLE IF EXISTS promotion;
CREATE TABLE IF NOT EXISTS promotion (
    id int GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    formation int NOT NULL,
    grade int NOT NULL,
    PRIMARY KEY (id)
);
DROP TABLE IF EXISTS student;
CREATE TABLE IF NOT EXISTS student (
    id int NOT NULL,
    INE int NOT NULL,
    id_promotion int NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (id)
        REFERENCES user (id),
    FOREIGN KEY (id_promotion)
        REFERENCES promotion (id)
);
DROP TABLE IF EXISTS teacher;
CREATE TABLE IF NOT EXISTS teacher (
    id int NOT NULL,
    NUMEN varchar(26) NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (id)
        REFERENCES user (id)
);
DROP TABLE IF EXISTS activity;
CREATE TABLE IF NOT EXISTS activity (
    id int GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    name varchar(26) NOT NULL,
    start_date timestamp NOT NULL,
    end_date timestamp NOT NULL,
    subject varchar(25) NOT NULL,
    id_promotion int NOT NULL,
    id_teacher int NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (id_promotion)
        REFERENCES promotion (id),
    FOREIGN KEY (id_teacher)
        REFERENCES teacher (id)
);
DROP TABLE IF EXISTS graduation;
CREATE TABLE IF NOT EXISTS graduation (
    id_student int NOT NULL,
    id_activity int NOT NULL,
    "grade" int NOT NULL,
    PRIMARY KEY (id_student, id_activity),
    FOREIGN KEY (id_student)
        REFERENCES student (id),
    FOREIGN KEY (id_activity)
        REFERENCES activity (id)
);
DROP TABLE IF EXISTS lesson;
CREATE TABLE IF NOT EXISTS lesson (
    id int GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    filePath varchar(500) NOT NULL,
    id_activity int NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (id_activity)
        REFERENCES activity (id)
);
DROP TABLE IF EXISTS "exercise";
CREATE TABLE IF NOT EXISTS "exercise" (
    id int GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    filePath varchar(500) NOT NULL,
    id_activity int NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (id_activity)
        REFERENCES activity (id)
);